name: 'Install'
description: 'Sets up Node.js and runs install'

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v4.2.0

    - name: Setup Node.js
      uses: actions/setup-node@v6.2.0
      with:
        node-version: 22.x
        registry-url: 'https://registry.npmjs.org'
        cache: 'pnpm'

    - name: Setup Git User
      shell: bash
      run: |
        git config --global user.email "joseshegs@gmail.com"
        git config --global user.name "Segun Adebayo"

    - name: Install dependencies
      shell: bash
      run: pnpm install
